### ISSUE TITLE
Create an example dashboard

### ISSUE THREAD

**Issue by chfritz** [transitiverobotics/transitive#60]
This would serve two purposes:

- show-case how easy it is to build out a "Robot Operations Center" using Transitive components
- some customers don't yet have their own web application could use this as a starting-point.

Stack:
- vite-express
- shadcn (incl. tailwind css)

### Front-end
- sidebar navigation: one tab each for
  - Devices
  - Video (webrtc-video)
  - Teleoperation (remote-teleop)
  - Terminal (terminal)
  - Health (health-monitoring)
  - Configuration (configuration-management)
  - (more later, incl. ros-tool and file-sync)
- body: the selected tab
  - Devices tab: list of active robots (similar to Portal)
  - all other tabs:
    - on top: dropdown to select the robot
    - then show the respective capability for that robot below

### Back-end
- authentication: username + password
  - can reuse code from the Portal for this
- an API endpoint to sign JWTs on-demand for authenticated users
- uses `.env` file to store (from transitiverobotics.com), filled in by user of the dashboard:
  - transitiverobotics.com account name,
  - robot token,
  - JWT secret.

### README

The README should suggest to users to fork the repo, fill in the values in the `.env` file, and how to start it (ideally just `npm start`).

**Comment by chfritz** [comment]
### Milestone 1
- [ ] @chfritz to create separate repo
- [ ] @jlurgo create account on transitiverobotics.com
  - [ ] @chfritz to set it to "free"
- [ ] @jlurgo to add test device to his account (e.g., using provided Docker container)
  - [ ] install capabilities
  - [ ] add capabilities to dashboard

### Milestone 2
- [ ] use SDK to get a list of active devices
